'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Bezoeker
    Public Property Id As Integer
    Public Property Ingelogde_Bezoeker As String
    Public Property Voornaam As String
    Public Property Achternaam As String
    Public Property Email As String
    Public Property Land As String
    Public Property Telefoon As String
    Public Property Onderwerp As String
    Public Property Bericht As String
    Public Property CreationDate As String

End Class
